# @Author       : Ruopeng Gao
# @Description  : Config for training DanceTrack.
#                 We change some parameters compared with our paper, looking forward more stable training convergence.

GIT_VERSION:

MODE: submit
CONFIG_PATH:
VISUALIZE: True
AVAILABLE_GPUS: 0,
DEVICE: cuda
OUTPUTS_DIR: ./outputs/putr_mot17/
USE_DISTRIBUTED: False

RESUME:
RESUME_SCHEDULER: True
MULTI_CHECKPOINT: False

# About submit
SUBMIT_MODEL: /home/lcw/hdd/projects/PuTR/outputs/putr_dancetrack/exp/固定512-6-train_2024-04-23-11-30/checkpoint_5.pth
SUBMIT_DATA_SPLIT: test
DET_SCORE_THRESH: 0.1
TRACK_SCORE_THRESH: 0.6
MISS_TOLERANCE: 15
MAX_NFRAMES: 30
MIN_TRACK_HITS: 3
NEW_TRK_TOLERANCE: 3
DETS_IOU_THRESH: 0.3


# About model
DIM: 512
N_LAYERS: 6
N_HEADS: 8
NORM_EPS: 1.0e-5
PATCH_GRID: 64
MAX_SEQ_LEN: 4096

# About data processing
DATASET: MOT17
USE_MOTSYNTH:
USE_CROWDHUMAN:
MOTSYNTH_RATE:
DATA_ROOT:
DATA_PATH:
NUM_WORKERS: 8
BATCH_SIZE: 64
ACCUMULATION_STEPS: 1
COCO_SIZE: False
OVERFLOW_BBOX: False
REVERSE_CLIP: 0.0
SEND_IMG: True


