GIT_VERSION:

MODE: submit
CONFIG_PATH:
VISUALIZE: False
AVAILABLE_GPUS: 0,
DEVICE: cuda
OUTPUTS_DIR: ./outputs/putr_dancetrack/
USE_DISTRIBUTED: False

# About submit
SUBMIT_MODEL:
SUBMIT_DATA_SPLIT: test
DET_SCORE_THRESH: 0.1
TRACK_SCORE_THRESH: 0.6
MISS_TOLERANCE: 30
MAX_NFRAMES: 30
MIN_TRACK_HITS: 3
NEW_TRK_TOLERANCE: 3
DETS_IOU_THRESH: 0.3
ASSO_THRE1: 0.2
ASSO_THRE2: 0.2

# About model
DIM: 512
N_LAYERS: 6
N_HEADS: 8
NORM_EPS: 1.0e-5
PATCH_GRID: 64

# About data processing
DATASET: DanceTrack
DATA_ROOT:



