# @Author       : Ruopeng Gao
# @Description  : Config for training DanceTrack.
#                 We change some parameters compared with our paper, looking forward more stable training convergence.

GIT_VERSION:

MODE: train
CONFIG_PATH:
VISUALIZE: False
AVAILABLE_GPUS: 0,
DEVICE: cuda
OUTPUTS_DIR: ./outputs/putr_dancetrack/
USE_DISTRIBUTED: False

RESUME:
RESUME_SCHEDULER: True
MULTI_CHECKPOINT: False

# About submit
SUBMIT_DIR:
SUBMIT_MODEL:
SUBMIT_DATA_SPLIT: test
DET_SCORE_THRESH: 0.5
TRACK_SCORE_THRESH: 0.5
RESULT_SCORE_THRESH: 0.5
MISS_TOLERANCE: 30
USE_MOTION: False
MOTION_MIN_LENGTH: 3
MOTION_MAX_LENGTH: 5
MOTION_LAMBDA: 0.5

# About Evaluation
EVAL_DIR:
EVAL_MODE: specific               # specific/continue
EVAL_MODEL:
EVAL_PORT:
EVAL_THREADS: 1
EVAL_DATA_SPLIT: val

# About data processing
DATASET: DanceTrack
USE_MOTSYNTH:
USE_CROWDHUMAN:
MOTSYNTH_RATE:
DATA_ROOT:
DATA_PATH:
NUM_WORKERS: 8
BATCH_SIZE: 64
ACCUMULATION_STEPS: 1
COCO_SIZE: False
OVERFLOW_BBOX: False
REVERSE_CLIP: 0.0
SEND_IMG: True

# About model
DIM: 256
N_LAYERS: 3
N_HEADS: 8
NORM_EPS: 1.0e-5
PATCH_GRID: 64
MAX_SEQ_LEN: 4096

# Pretrain model
PRETRAINED_MODEL:

# Sampling setting
SAMPLE_STEPS: [2, 4, 6]
SAMPLE_LENGTHS: [2, 4, 6, 8]
SAMPLE_MODES: [random_interval]
SAMPLE_INTERVALS: [10]

# Training setting
SEED: 42
EPOCHS: 8
DROP_OUT: 0.0
LR: 2.0e-4
WEIGHT_DECAY: 0.0005
CLIP_MAX_NORM: 1.0
LR_SCHEDULER: Cosine
LR_DROP_RATE:
LR_DROP_MILESTONES:
